trigger:
- main

pool:
  name: LucasPool
  demands: 
  - msbuild
  - visualstudio
  - vstest
  - javac

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
  
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '**/*.sln'
    
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: 'Release'
    

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(BuildConfiguration)'