trigger:
- main

pool:
  name: vmlucas01

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'
    includePreviewVersions: true

- script: dotnet tool install --global WebDriverManager.ConsoleApp
  displayName: 'Install WebDriverManager'

- script: |
    .\tools\WebDriverManager.ConsoleApp.2.11.2\WebDriverManager.exe chrome
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: 'Download and configure ChromeDriver'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --no-build'
